DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS CurrentTime;

CREATE TABLE Items (
  Item_ID INTEGER PRIMARY KEY,
  Seller_ID VARCHAR(100) NOT NULL,
  Name VARCHAR(200) NOT NULL,
  Buy_Price NUMERIC(10,2),
  First_Bid NUMERIC(10,2) NOT NULL,
  Current_Price NUMERIC(10,2) NOT NULL,
  Number_of_Bids INTEGER NOT NULL,
  Starts TIMESTAMP NOT NULL,
  Ends TIMESTAMP NOT NULL CHECK (Ends > Starts),
  Description TEXT NOT NULL,
  FOREIGN KEY (Seller_ID) REFERENCES Users DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE Users (
  User_ID VARCHAR(100) PRIMARY KEY,
  Rating INTEGER NOT NULL,
  Location VARCHAR(200),
  Country VARCHAR(100)
);

CREATE TABLE Category (
  Item_ID INTEGER NOT NULL,
  Category VARCHAR(100) NOT NULL,
  FOREIGN KEY (Item_ID) REFERENCES Items DEFERRABLE INITIALLY DEFERRED,
  PRIMARY KEY (Item_ID, Category)
);

CREATE TABLE Bids (
  Item_ID INTEGER NOT NULL,
  User_ID VARCHAR(100) NOT NULL,
  Time TIMESTAMP NOT NULL,
  Amount NUMERIC(10,2) NOT NULL,
  CONSTRAINT Bid_ID PRIMARY KEY (Item_ID, User_ID, Amount),
  FOREIGN Key (Item_ID) REFERENCES Items DEFERRABLE INITIALLY DEFERRED,
  FOREIGN Key (User_ID) REFERENCES Users DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE CurrentTime (
  Time TIMESTAMP NOT NULL
);
INSERT INTO CurrentTime VALUES('2001-12-20 00:00:01');
SELECT * FROM CurrentTime;
